// <auto-generated />
namespace PhongTot.Entities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addemailtemplate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addemailtemplate));
        
        string IMigrationMetadata.Id
        {
            get { return "201612200851332_addemailtemplate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
